# Generated by Django 4.2.6 on 2023-10-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_manageractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageractionlog',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
