version: '3.3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: daphne backend.asgi:application --port 8000 --bind 0.0.0.0
    volumes:
      - ./backend:/app
      - ./static:/app/static
    ports:
      - "8002:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1

  redis:
    image: "redis:alpine"
    ports:
      - "6378:6379"

  react-app:
    container_name: iitu-queue-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
