version: '3.8'

services:
#  nginx:
#    image: nginx:alpine
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./media:/media
#    ports:
#      - "8080:80"  # Changed from "80:80" to "8080:80"
#    depends_on:
#      - web
  web:
    build: .
    command: daphne backend.asgi:application --port 8000 --bind 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
