# Generated by Django 4.2.6 on 2023-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='currently_serving',
            field=models.IntegerField(default=0),
        ),
    ]
