# Generated by Django 4.2.6 on 2023-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_qr', '0003_queueticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
